### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by wangw42** [DAEUN28/Mongli-Server#1]
Hey! 😊 
I'd like to use your server to do my homework, but it seems the server cant work. Would u like to fix it?
Thank u so much!!!!

**Comment by DAEUN28** [comment]
Hello. Thank you for your interest in my project :) 
But Mongli-Server in AWS is deprecated.
So If you want using my code, You can just follow this step.

First, download my project from GitHub.
Second, for using JWT, follow this [link](https://github.com/DAEUN28/Mongli-Server#for-using-jwt)
Third, run a server using Xcode.
If you finish all of this normally, Finally, you can use your local server!!!

**Comment by wangw42** [comment]
get it!!!
Thank u so much😄
